### YamlMime:UniversalReference
ms.openlocfilehash: 777051058935475aebf2055932882ec0cd21fea9
ms.sourcegitcommit: efa2d98deffe8a0d41a8d63f9f07aa720862e6ab
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 12/13/2018
ms.locfileid: "52135177"
items:
- uid: azure-servicefabric.TestErrorChaosEvent
  name: TestErrorChaosEvent
  fullName: TestErrorChaosEvent
  children:
  - azure-servicefabric.TestErrorChaosEvent.reason
  langs:
  - typeScript
  type: interface
  summary: >-
    Chaos エンジンで予期しないイベントが発生したときに生成される混乱イベントについて説明します。

    たとえば、エンティティの障害発生中に一貫性があり、中、クラスター スナップショットにより Chaos が見つかりましたこと、エンティティが既にエラーが発生しました--予期しないイベントであります。
  extends:
    name: azure-servicefabric.ChaosEvent
  package: azure-servicefabric
- uid: azure-servicefabric.TestErrorChaosEvent.reason
  name: reason
  fullName: reason
  children: []
  langs:
  - typeScript
  type: property
  summary: TestErrorChaosEvent が生成された理由について説明します。 たとえば、Chaos はしようとするパーティションの障害が、TestErrorEvent が生成される、パーティションは、フォールト トレラントではない理由を示すそのパーティションは、フォールト トレラントでは不要になったを検索します。
  optional: true
  syntax:
    content: 'reason?: string'
    return:
      type:
      - string
  package: azure-servicefabric
references:
- uid: azure-servicefabric.ChaosEvent
  name: ChaosEvent
  spec.typeScript:
  - name: ChaosEvent
    fullName: ChaosEvent
    uid: azure-servicefabric.ChaosEvent
